README.md
lua/telescope/_extensions/project.lua
lua/telescope/_extensions/project_actions.lua

You can now pass in `{ change_dir = true }` to the `.projects` function. When true, this will change directories when a project is selected. This is useful because it updates any file manages such as `NvimTree` to be in that directory.
Example:
```lua
require'telescope'.extensions.project.project{ change_dir = true }
```

Added a `change_dir` option which `cd`s into the select project

---

README.md
lua/telescope/_extensions/project.lua
lua/telescope/_extensions/project_actions.lua

Adds a function (and associated keymap) to rename projects.
---
The rename function is basically a modified version of the delete function that prompts the user for a new name.
Currently, the prompt value defaults to the current name, but depending on preference, it may be better to default to nothing.
I'm happy to change this if other people think one way or the other is better.

Add rename function

---

lua/telescope/_extensions/project/finders.lua
lua/telescope/_extensions/project/git.lua

fixes #35
* switch to plenary.strings instead of telescope.utils
* fix mismatched keys between `widths.dir` and `project.display_path` (display_path seemed like the more descriptive key so I used that)
* fixes update_git_repos trying to parse `/tmp/found_projects.txt` when we had just skipped creating it

Fix errors in #35

---

lua/telescope/_extensions/project/main.lua
lua/telescope/_extensions/project/utils.lua
lua/tests/utils_spec.lua

Projects that do not exist anymore on the system should not be displayed in `projects` picker.
Add a `cleanup_missing_projects` utility that will run at setup (each time neovim session is started) which will remove projects from `telescope-projects.txt` where the file path does not exist in file system. Also during a given session, filter out projects whose paths' do not exist.

feat: handle missing project paths

---

lua/telescope/_extensions/project/actions.lua
lua/telescope/_extensions/project/finders.lua
lua/telescope/_extensions/project/main.lua
lua/telescope/_extensions/project/utils.lua
lua/tests/utils_spec.lua

Hi @claidler as we discussed in #37 this is a safer approach to filtering out projects that do not exist on file system.
The last attempt, I tried to modify the underlying file, but that had unintentional consequences. Hopefully this implementation does what it is supposed to do. I tested it with the test case that you described in #37 and it worked fine. 
Please have a look when you have a chance 🙂

feat: label project paths that do not exist

---

lua/telescope/_extensions/project/git.lua

This fixes an issue where auto-discovered projects don't show
up in the projects list the very first time the project function
is run.

Close file handle after saving projects

---

lua/telescope/_extensions/project/git.lua

OSX's find command doesn't have the `-printf` flag

Fix find command for OSX

---

README.md
lua/telescope/_extensions/project/actions.lua
lua/telescope/_extensions/project/main.lua

Hello,
I missed having option to see hidden files in projects. Especially in my `dotfiles` repo.
This adds ability to toggle hidden files in `find_files` builtin using `hidden_files` variable from `setup`.

Show hidden files in selected project

---

lua/telescope/_extensions/project/actions.lua

We currently use `telescope.actions.get_selected_entry` in our internal actions.
This is deprecated in favour of `telescope.actions.state.get_selected_entry`, causing a logging message every time a project is selected.
This PR switches to the new functions.

fix: don't use deprecated actions

---

lua/telescope/_extensions/project/utils.lua

Fix regex to allow telescope-project.nvim to parse pathes ended with '/' correctly.

fix: parse pathes ended with '/' correctly

---

README.md

The example around line 100 doesn't work initially.
Add missing curly brace so no syntax error is thrown when copying the example.
There's a chance this was intentional, such as showing that this project's setup is a continuation of the `require('telescope').setup()` call. In that case, I think there's more beginner-friendly and clearer ways to signal that intent, which I can work on if necessary!

fix: config example in README

---

lua/telescope/_extensions/project/utils.lua

fix https://github.com/nvim-telescope/telescope-project.nvim/issues/113

fix: move focus to previous buffer after nvimtree.open()

---

README.md
lua/telescope/_extensions/project/main.lua
lua/telescope/_extensions/project/utils.lua

Hello, here is the fix for recent open project sort and order by setting feature.
In my tests this method not worked as expected
```
M.get_last_accessed_time = function(path)
local expanded_path = vim.fn.expand(path)
local fs_stat = vim.loop.fs_stat(expanded_path)
return fs_stat and fs_stat.atime.sec or 0
end
```
When project change via plugin the **atime** of folder not changed so that we always have same time there and projects are not ordered as expected. However if I use GUI (the finder in my PC) and go to the project folder > the **atime** change.
As a workaround I stored the last accessed time in project string.
In addition added new setting **order_by** so that we can order projects asc, desc and recent(default)
Please check if it's ok for you
Thanks

feat/order: fix order by recently opened, add order by setting

---

lua/telescope/_extensions/project/git.lua

Currently, I am running into a problem that the path of the added project is after some color sequence coding:
Maybe it is due to my `$COLORTERM='truecolor'`.
Part of my `:checkhealth`: 
```
- INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
- INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
- INFO: $TERM_PROGRAM='WezTerm'
- INFO: $COLORTERM='truecolor'
```
So I go to `try_and_find_git_path` in `util.lua`, use `gsub` to remove the whole color sequence, which could be invisible on github rendering since it contains the ascii control sequence. They are displayed as "^[" (esc) and "^G" in my neovim:

Use `gsub` to remove ansi-rgb term output after getting `git_root` from `vim.fn.systemlist`

---

README.md
lua/telescope/_extensions/project/main.lua

This PR allows the user to configure Telescope Project to invoke any arbitrary function as the result of a project being selected. Existing behavior remains unchanged and the user must opt-in to this configuration option.
Example:
```lua
local project_actions = require("telescope._extensions.project.actions")
require('telescope').setup({
extensions = {
project = {
on_project_selected = function(prompt_bufnr)
project_actions.change_working_directory(prompt_bufnr, false)
require("harpoon.ui").nav_file(1)
end
}
}
})
require'telescope'.load_extension('project')
```
Closes #119

Add ability to change default action

---

README.md
lua/telescope/_extensions/project/finders.lua

If `search_by` is a table, it adds the option to search by both path and title, by concatenating properties separated by space

add option to use both title and path searching

---

lua/telescope/_extensions/project/actions.lua

The extension didn't have any method for users to add their own projects to it manually.
I wanted to write my own project root directory finder and then add those projects to telescope. This is a good telescope project picker, but it didn't support me adding the projects I found with my own logic.

Add add_project_path action

---

lua/telescope/_extensions/project/finders.lua
lua/telescope/_extensions/project/project.lua
lua/telescope/_extensions/project/utils.lua

The equals sign and the linefeed characters are both valid in file and directory names.
The previous encoding format: https://github.com/nvim-telescope/telescope-project.nvim/blob/34dfa6daa88c132e9e297ff5bd515801a8195eeb/lua/telescope/_extensions/project/utils.lua#L97-L103) 
The previous encoding format breaks when the paths to the projects have equal signs `=` in them, or newlines.
My new representation escapes newlines and equal signs that aren't the intended field separators, so every project is guaranteed to be serialized to a single line, that doesn't lose any information about where fields begin and end.
I made sure the new format is as backwards-compatible as possible with the previous format; the only users who may be affected would have to have `=`, `\`, `\n` characters in their …

Add support for = and newline in project paths

---

README.md
lua/telescope/_extensions/project/git.lua
lua/telescope/_extensions/project/main.lua

This adds an option to the setup config to not show a warning if one or more directories listed in the "base_dirs" table is missing.
Resolves #169

Add 'ignore_missing_dirs' option to not show warnings when one or more base_dirs are missing.

---

lua/telescope/_extensions/project/main.lua

C-w should really be used to delete a backwards word ,  currently if you press C-w when you started to type something by mistake it errors out with an exception.

Replace C-w with C-c
